name: Flowhub
favicon: null
layout_spectrum: 0.30539
typography_spectrum: 0.77668
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#091416'
    - '#e90262'
    - '#0bb8da'
    - '#ffffff'
    - '#535d6c'
  brandStrength: 0.8
  lightness: 0.0625
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
