analytics: {}
color:
  brandColors:
    - '#091416'
    - '#e90262'
    - '#0bb8da'
    - '#ffffff'
    - '#626d6f'
  brandStrength: 0.351351
  lightness: 0.1875
  rhythmicContrast: 0.75
  saturation: 0.5625
cta: {}
layout_spectrum: 0.62295
name: Flowhub
opengraph: {}
purpose: []
typography_spectrum: 0.6951
