typography_spectrum: 0.5002055359072983
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.8091102663893253
  lightness: 0.16174883302301168
  rhythmicContrast: 0.7785116084851325
  saturation: 0.4518469150643796
github: true
opengraph: {}
layout_spectrum: 0.8454538772348315
analytics: {}
name: Flowhub
cta: {}
navigation:
  - name: Flowhub IDE webapp
    url: app.flowhub.io
    type: external
  - name: Flowhub Chrome app
    url: >-
      https://chrome.google.com/webstore/detail/flowhub/aacpjichompfhafnciggfpfdpfododlk
    type: external
  - name: NoFlo.JS
    url: noflojs.org
    type: external
  - name: MsgFlo
    url: 'https://msgflo.org'
    type: external
purpose:
  - type: external
    url: 'http://app.flowhub.io'
    label: Try Flowhub now
