name: Flowhub
favicon: null
layout_spectrum: 0.8
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060604'
    - '#600000'
    - '#1a1e2a'
    - '#a51b1b'
    - '#62231c'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
