name: Flowhub
favicon: null
layout_spectrum: 0.83848
typography_spectrum: 0.6951
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#091416'
    - '#e90262'
    - '#0bb8da'
    - '#ffffff'
    - '#626d6f'
  brandStrength: 0.8125
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
