typography_spectrum: 0.2663107549306005
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.8091102663893253
  lightness: 0.16174883302301168
  rhythmicContrast: 0.7785116084851325
  saturation: 0.4518469150643796
github: true
opengraph: {}
layout_spectrum: 0.13883351790718734
analytics: {}
name: Flowhub
cta: {}
navigation:
  - name: MsgFlo
    url: 'https://msgflo.org'
    type: external
  - name: Webapp
    url: 'http://app.flowhub.io'
    type: external
  - name: Chrome app
    url: >-
      https://chrome.google.com/webstore/detail/flowhub/aacpjichompfhafnciggfpfdpfododlk
    type: external
  - name: NoFlo.js
    url: 'https://noflojs.org'
    type: external
  - name: Documentation
    url: 'http://docs.flowhub.io/'
    type: external
content: []
purpose:
  - type: external
    url: 'http://app.flowhub.io'
    label: Try Flowhub now
