layout_spectrum: 0.7700516958442507
typography_spectrum: 0.3064202155572095
color:
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  brandStrength: 0.35604839826297785
  lightness: 0.36732250431653957
  saturation: 0.3935885072792742
  rhythmicContrast: 0.6239917654588376
name: Flowhub Blog
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4a020c4e-9f6f-4552-9ecb-987f26162e4d.ico
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/de9d0983-00f1-4ddb-a7b7-d9b73d809bc2.png
cta: {}
analytics:
  facebook: ''
  google: UA-46363984-3
  twitter: ''
opengraph:
  type: ''
  appId: ''
purpose:
  - type: external
    label: Try Flowhub now
    url: 'http://app.flowhub.io'
title: Flowhub Blog
description: News about Flowhub & FBP programming
author: {}
content_rating:
  adult: false
navigation:
  - name: Documentation
    url: 'https://docs.flowhub.io/'
    type: external
  - name: About Us
    url: 'https://flowhub.io/about/'
    type: external
content: []
github: true
